net_type: api0lw8421ew1repw10poly1lg
single_parnet_type: transformer_type
multi_parnet_type: gnn_identity
readout_net_type: mlp_type
trans_layer: 2
gnn_layer: 2
nnode: 128
tau_long: 0.1
window_sliding: 8
batch_size: 2
ngrid: 12
b:
  - 0.2
a:
  - 0
nitr: 1000
loss_weights:
  - 0
  - 0.125
  - 0
  - 0.25
  - 0
  - 0.5
  - 0
  - 1
ew: 1
repw: 10
poly_deg: 1
maxlr: 1e-5
region: 'lg'
dpt_train: 90000
dpt_valid: 10000
start_epoch: 0
loadfile: null  # null means None