#!/bin/sh
#PBS -q parallel
#PBS -l nodes=1:ppn=8:slave
#PBS -N flbd0.1e2720rho0.38l1
#PBS -V 
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
echo $PBS_NODEFILE


#slep 2
######################################
conda activate py37
e#####################################
#./f-run-lambda0.0.1reg.sh > ./log/f-auto-lbd0.0.1reg.log
./f-run-metric.sh 0.38
######################################
conda deactivate
######################################
sleep 2
