#!/bin/sh
#PBS -q parallel
#PBS -l nodes=1:ppn=8:slave
#PBS -N pwlbd0.0e4400rho0.38l2
#PBS -V 
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
echo $PBS_NODEFILE


#sleep 2
######################################
conda activate py37
######################################
#./pw-run-lambda0.0.38reg.sh > ./log/pw-auto-lbd0.0.38reg.log
./pw-run-metric.sh 0.38
######################################
conda deactivate
######################################
sleep 2
