#!/bin/sh
#PBS -q parallel
#PBS -l nodes=1:ppn=8:spark
#PBS -N log-fpw-auto-bs40lambda0.01decay200
#PBS -V 
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
echo $PBS_NODEFILE


#sleep 2
######################################
conda activate py37
######################################
./fpw-run-bs40lambda0.01decay200.sh > ./log/fpw-auto-bs40lambda0.01decay200.log
#CUDA_VISIBLE_DEVICES='' python MD_sampler.py ../data/gen_by_MD/pw-n16rho0.2T0.71-hard1-e20990/MD_config.dict ../data/gen_by_MD/pw-n16rho0.2T0.71-hard1-e20990/ML_config.dict  > ./log/pw-n16rho0.2T0.71hard1e20990.log
#CUDA_VISIBLE_DEVICES='' python MD_sampler.py ../data/gen_by_MD/crash_data2/pw-n4T0.03-soft2/MD_config.dict ../data/gen_by_MD/crash_data2/pw-n4T0.03-soft2/ML_config.dict > ./log/pw-n4T0.03label2.log
######################################
conda deactivate
######################################
sleep 2
